# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='gender',
            new_name='sex',
        ),
    ]
