# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.CharField(choices=[('CCS', 'College of Computer Science'), ('RVRCOB', 'Ramon V del Rosario College of Business'), ('CLA', 'College of Liberal Arts'), ('SOE', 'School of Economics'), ('GCOE', 'Gokongwei College of Engineering'), ('COL', 'College of Law'), ('BAGCED', 'Brother Andrew Gonzales College of Education')], max_length=6),
        ),
    ]
