# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20171102_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprogram',
            name='date_expected_return',
            field=models.DateField(null=True),
        ),
    ]
