# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20171031_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
