# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20171031_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residencyaddresshistory',
            old_name='residence_type',
            new_name='residence',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='type',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='gender',
            new_name='sex',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
