# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20171101_0531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residencyaddresshistory',
            old_name='residence_type',
            new_name='residence',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='type',
            new_name='category',
        ),
    ]
