# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20171101_0531'),
        ('students', '0004_auto_20171101_0602'),
    ]

    operations = [
    ]
