# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-05 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
