# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20171105_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprogram',
            name='program_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Program'),
        ),
    ]
