# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20171107_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencyaddresshistory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprogram',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
