# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20171109_0504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprogram',
            old_name='program_offering',
            new_name='program',
        ),
        migrations.AddField(
            model_name='studentprogram',
            name='default_units',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
