# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20171111_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprogram',
            old_name='program',
            new_name='study_field',
        ),
    ]
