# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0022_auto_20171111_1345'),
        ('students', '0015_auto_20171111_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogram',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.Term'),
        ),
    ]
