# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20171111_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprogram',
            name='term',
        ),
    ]
