# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0027_program_terms'),
        ('students', '0018_remove_studentprogram_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogram',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institutions.Term'),
            preserve_default=False,
        ),
    ]
