# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_studentprogram_term'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residencyaddresshistory',
            old_name='deleted_at',
            new_name='archived_at',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='deleted_at',
            new_name='archived_at',
        ),
        migrations.RenameField(
            model_name='studentprogram',
            old_name='deleted_at',
            new_name='archived_at',
        ),
    ]
