# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_auto_20171115_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residencyaddresshistory',
            old_name='user',
            new_name='archiver',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='archiver',
        ),
        migrations.RenameField(
            model_name='studentprogram',
            old_name='user',
            new_name='archiver',
        ),
    ]
