# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_auto_20171115_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residencyaddresshistory',
            old_name='effective_from',
            new_name='date_effective',
        ),
    ]
