# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0035_auto_20171121_0815'),
        ('students', '0025_auto_20171120_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployedStudentProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archiver', models.CharField(blank=True, max_length=32)),
                ('default_units', models.PositiveIntegerField()),
                ('date_expected_return', models.DateField(null=True)),
                ('total_units_enrolled', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InboundStudentProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archiver', models.CharField(blank=True, max_length=32)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.InboundProgram')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutboundStudentProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archiver', models.CharField(blank=True, max_length=32)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.OutboundProgram')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archiver', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.OutboundProgram')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentApplicationRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archiver', models.CharField(blank=True, max_length=32)),
                ('is_accomplished', models.BooleanField(default=False)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Requirement')),
                ('student_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.OutboundStudentProgram')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='studentprogram',
            name='date_expected_return',
        ),
        migrations.RemoveField(
            model_name='studentprogram',
            name='default_units',
        ),
        migrations.RemoveField(
            model_name='studentprogram',
            name='program',
        ),
        migrations.RemoveField(
            model_name='studentprogram',
            name='term',
        ),
        migrations.RemoveField(
            model_name='studentprogram',
            name='total_units_enrolled',
        ),
        migrations.AddField(
            model_name='student',
            name='is_graduate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprogram',
            name='terms_duration',
            field=models.ManyToManyField(to='institutions.Term'),
        ),
        migrations.AddField(
            model_name='outboundstudentprogram',
            name='student_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentProgram'),
        ),
        migrations.AddField(
            model_name='inboundstudentprogram',
            name='student_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentProgram'),
        ),
        migrations.AddField(
            model_name='deployedstudentprogram',
            name='student_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.OutboundStudentProgram'),
        ),
    ]
