# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-24 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0036_requirement'),
        ('students', '0027_auto_20171124_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplicationrequirement',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='studentapplicationrequirement',
            name='student_program',
        ),
        migrations.AddField(
            model_name='outboundstudentprogram',
            name='application_requirement',
            field=models.ManyToManyField(to='institutions.Requirement'),
        ),
        migrations.DeleteModel(
            name='StudentApplicationRequirement',
        ),
    ]
