# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-24 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0036_requirement'),
        ('students', '0028_auto_20171124_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundstudentprogram',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inboundstudentprogram',
            name='study_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.StudyField'),
        ),
        migrations.AddField(
            model_name='inboundstudentprogram',
            name='terms_duration',
            field=models.ManyToManyField(to='institutions.Term'),
        ),
        migrations.AddField(
            model_name='outboundstudentprogram',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundstudentprogram',
            name='study_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.StudyField'),
        ),
        migrations.AddField(
            model_name='outboundstudentprogram',
            name='terms_duration',
            field=models.ManyToManyField(to='institutions.Term'),
        ),
    ]
