# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-24 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_auto_20171124_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprogram',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentprogram',
            name='study_field',
        ),
        migrations.RemoveField(
            model_name='studentprogram',
            name='terms_duration',
        ),
        migrations.RemoveField(
            model_name='inboundstudentprogram',
            name='student_program',
        ),
        migrations.RemoveField(
            model_name='outboundstudentprogram',
            name='student_program',
        ),
        migrations.DeleteModel(
            name='StudentProgram',
        ),
    ]
