# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-24 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_auto_20171124_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundstudentprogram',
            name='total_units_enrolled',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
