# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-24 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_inboundstudentprogram_total_units_enrolled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outboundstudentprogram',
            old_name='application_requirement',
            new_name='application_requirements',
        ),
    ]
