# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0035_auto_20171124_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outboundstudentprogram',
            old_name='application_requirement',
            new_name='application_requirements',
        ),
    ]
