# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0036_auto_20171126_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboundstudentprogram',
            name='study_field',
        ),
        migrations.RemoveField(
            model_name='outboundstudentprogram',
            name='study_field',
        ),
    ]
