# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-02 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0037_auto_20171201_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedStudentProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archiver', models.CharField(blank=True, max_length=32)),
                ('total_units_enrolled', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InboundCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archiver', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='inboundstudentprogram',
            name='total_units_enrolled',
        ),
        migrations.AddField(
            model_name='acceptedstudentprogram',
            name='student_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.InboundStudentProgram'),
        ),
        migrations.AddField(
            model_name='inboundstudentprogram',
            name='inbound_courses',
            field=models.ManyToManyField(blank=True, to='students.InboundCourse'),
        ),
    ]
