# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-02 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0038_auto_20171202_0731'),
        ('students', '0038_auto_20171202_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundstudentprogram',
            name='application_requirements',
            field=models.ManyToManyField(blank=True, to='institutions.InboundRequirement'),
        ),
    ]
