# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-02 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0039_inboundstudentprogram_application_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptedstudentprogram',
            name='student_program',
        ),
        migrations.DeleteModel(
            name='AcceptedStudentProgram',
        ),
    ]
