# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-02 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0040_auto_20171202_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedStudentProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archiver', models.CharField(blank=True, max_length=32)),
                ('total_units_enrolled', models.PositiveIntegerField()),
                ('student_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.InboundStudentProgram')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
