# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0041_acceptedstudentprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundstudentprogram',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AlterField(
            model_name='outboundstudentprogram',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
