# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0042_auto_20171204_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outboundstudentprogram',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='outboundstudentprogram',
            name='archiver',
        ),
    ]
