# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Continent')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=256, null=True)),
                ('address', models.CharField(max_length=256)),
                ('website', models.CharField(max_length=256)),
                ('contact_person_name', models.CharField(max_length=256, null=True)),
                ('contact_person_number', models.CharField(max_length=64, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Country')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionMemorandum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement', models.CharField(choices=[('B', 'Bilateral'), ('M', 'Multilateral')], max_length=12)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='MemorandumVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorandum_category', models.CharField(choices=[('MOA', 'Memorandum of Agreement'), ('MOU', 'Memorandum of Understanding')], max_length=3)),
                ('memorandum_file', models.CharField(max_length=512)),
                ('version_date', models.DateField()),
                ('date_effective', models.DateField()),
                ('date_expiration', models.DateField(null=True)),
                ('college_initiator', models.CharField(choices=[('CCS', 'College of Computer Science'), ('RVRCOB', 'Ramon V del Rosario College of Business'), ('CLA', 'College of Liberal Arts'), ('SOE', 'School of Economics'), ('GCOE', 'Gokongwei College of Engineering'), ('COL', 'College of Law'), ('BAGCED', 'Brother Andrew Gonzales College of Education')], max_length=5, null=True)),
                ('memorandum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.InstitutionMemorandum')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkage', models.CharField(choices=[('S', 'Scholarship'), ('OI', 'OJT/Internship'), ('FE', 'Faculty Exchange'), ('SE', 'Student Exchange'), ('RE', 'Researcher / Expert Exchange'), ('SP', 'Support for Projects Exchange'), ('RP', 'Research and Publication'), ('AP', 'Academic Program'), ('PF', 'Project Funding'), ('EMPI', 'Exchange of Materials, Publications and Information'), ('CE', 'Cultural Exchange'), ('SAMC', 'Seminars and Academic Meetings / Conferences'), ('TAP', 'Technical or Administrative Programs'), ('O', 'Established Office'), ('ASE', 'Administrative and Staff Exchange'), ('EM', 'Executive Meetings')], max_length=4)),
                ('name', models.CharField(max_length=64)),
                ('memorandum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.InstitutionMemorandum')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Program')),
            ],
        ),
    ]
