# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorandum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MOA', 'Memorandum of Agreement'), ('MOU', 'Memorandum of Understanding')], max_length=3)),
                ('memorandum_file', models.CharField(max_length=512)),
                ('version_date', models.DateField()),
                ('date_effective', models.DateField()),
                ('date_expiration', models.DateField(null=True)),
                ('college_initiator', models.CharField(choices=[('CCS', 'College of Computer Science'), ('RVRCOB', 'Ramon V del Rosario College of Business'), ('CLA', 'College of Liberal Arts'), ('SOE', 'School of Economics'), ('GCOE', 'Gokongwei College of Engineering'), ('COL', 'College of Law'), ('BAGCED', 'Brother Andrew Gonzales College of Education')], max_length=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='institutionmemorandum',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='memorandumversion',
            name='memorandum',
        ),
        migrations.RemoveField(
            model_name='program',
            name='memorandum',
        ),
        migrations.AddField(
            model_name='institution',
            name='agreement',
            field=models.CharField(choices=[('B', 'Bilateral'), ('M', 'Multilateral')], default='B', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InstitutionMemorandum',
        ),
        migrations.DeleteModel(
            name='MemorandumVersion',
        ),
        migrations.AddField(
            model_name='memorandum',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution'),
        ),
    ]
