# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_auto_20171103_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='email',
            new_name='contact_person_email',
        ),
    ]
