# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-30 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_auto_20171030_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='contact_person_name',
        ),
    ]
