# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_auto_20171103_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorandum',
            name='version_date',
        ),
    ]
