# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-30 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_remove_institution_contact_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='contact_person_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
