# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_auto_20171101_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionMemorandum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement', models.CharField(choices=[('B', 'Bilateral'), ('M', 'Multilateral')], max_length=12)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution')),
            ],
        ),
        migrations.RemoveField(
            model_name='memorandum',
            name='institution',
        ),
        migrations.DeleteModel(
            name='Memorandum',
        ),
    ]
