# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_auto_20171103_2356'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memorandumlinkage',
            unique_together=set([('linkage', 'memorandum')]),
        ),
    ]
