# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0008_auto_20171101_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorandumVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorandum_category', models.CharField(choices=[('MOA', 'Memorandum of Agreement'), ('MOU', 'Memorandum of Understanding')], max_length=3)),
                ('memorandum_file', models.CharField(max_length=512)),
                ('version_date', models.DateField()),
                ('date_effective', models.DateField()),
                ('date_expiration', models.DateField(null=True)),
                ('college_initiator', models.CharField(choices=[('CCS', 'College of Computer Science'), ('RVRCOB', 'Ramon V del Rosario College of Business'), ('CLA', 'College of Liberal Arts'), ('SOE', 'School of Economics'), ('GCOE', 'Gokongwei College of Engineering'), ('COL', 'College of Law'), ('BAGCED', 'Brother Andrew Gonzales College of Education')], max_length=5, null=True)),
                ('memorandum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.InstitutionMemorandum')),
            ],
        ),
    ]
