# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0008_auto_20171103_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='contact_person_name',
            field=models.CharField(blank=True, default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institution',
            name='contact_person_number',
            field=models.CharField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memorandum',
            name='college_initiator',
            field=models.CharField(blank=True, choices=[('CCS', 'College of Computer Science'), ('RVRCOB', 'Ramon V del Rosario College of Business'), ('CLA', 'College of Liberal Arts'), ('SOE', 'School of Economics'), ('GCOE', 'Gokongwei College of Engineering'), ('COL', 'College of Law'), ('BAGCED', 'Brother Andrew Gonzales College of Education')], default='', max_length=5),
            preserve_default=False,
        ),
    ]
