# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0011_auto_20171104_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorandum',
            name='college_initiator',
            field=models.CharField(choices=[('CCS', 'College of Computer Science'), ('RVRCOB', 'Ramon V del Rosario College of Business'), ('CLA', 'College of Liberal Arts'), ('SOE', 'School of Economics'), ('GCOE', 'Gokongwei College of Engineering'), ('COL', 'College of Law'), ('BAGCED', 'Brother Andrew Gonzales College of Education')], max_length=5, null=True),
        ),
    ]
