# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0012_auto_20171105_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linkage',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='memorandumlinkage',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='memorandumlinkage',
            name='memorandum',
        ),
        migrations.RemoveField(
            model_name='program',
            name='memorandum_linkage',
        ),
        migrations.AddField(
            model_name='program',
            name='memorandum',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='institutions.Memorandum'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MemorandumLinkage',
        ),
        migrations.AddField(
            model_name='memorandum',
            name='linkages',
            field=models.ManyToManyField(to='institutions.Linkage'),
        ),
        migrations.AddField(
            model_name='program',
            name='linkage',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='institutions.Linkage'),
            preserve_default=False,
        ),
    ]
