# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20171107_0757'),
        ('institutions', '0013_auto_20171105_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programoffering',
            name='program',
        ),
        migrations.AddField(
            model_name='program',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProgramOffering',
        ),
    ]
