# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 05:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0017_auto_20171109_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='program',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='program',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='program',
            name='start_date',
        ),
        migrations.AddField(
            model_name='program',
            name='academic_year_start',
            field=models.PositiveIntegerField(default=1, max_length=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='terms',
            field=models.ManyToManyField(to='institutions.Term'),
        ),
        migrations.AddField(
            model_name='studyfield',
            name='terms',
            field=models.ManyToManyField(to='institutions.Term'),
        ),
    ]
