# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0018_auto_20171110_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year_start', models.PositiveIntegerField(max_length=9999)),
            ],
        ),
        migrations.RemoveField(
            model_name='program',
            name='academic_year_start',
        ),
        migrations.AddField(
            model_name='program',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institutions.AcademicYear'),
            preserve_default=False,
        ),
    ]
