# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0019_auto_20171110_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='academic_year_start',
            field=models.PositiveIntegerField(),
        ),
    ]
