# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0020_auto_20171110_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='id',
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='academic_year_start',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
