# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0021_auto_20171111_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyfield',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='term',
            name='name',
        ),
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institutions.AcademicYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
