# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0022_auto_20171111_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='term',
            name='start_date',
            field=models.DateField(),
        ),
    ]
