# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_remove_studentprogram_term'),
        ('institutions', '0024_auto_20171111_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='term',
            name='user',
        ),
        migrations.RemoveField(
            model_name='program',
            name='terms',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
    ]
