# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0026_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='terms',
            field=models.ManyToManyField(to='institutions.Term'),
        ),
    ]
