# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0029_auto_20171112_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='institutions.AcademicYear'),
        ),
    ]
