# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0030_auto_20171114_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='deleted_at',
            new_name='archived_at',
        ),
        migrations.RenameField(
            model_name='memorandum',
            old_name='deleted_at',
            new_name='archived_at',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='deleted_at',
            new_name='archived_at',
        ),
        migrations.RenameField(
            model_name='studyfield',
            old_name='deleted_at',
            new_name='archived_at',
        ),
        migrations.RenameField(
            model_name='term',
            old_name='deleted_at',
            new_name='archived_at',
        ),
    ]
