# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0031_auto_20171115_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='user',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memorandum',
            name='user',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='user',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studyfield',
            name='user',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='term',
            name='user',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
    ]
