# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-17 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0033_auto_20171115_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='memorandum',
        ),
        migrations.AddField(
            model_name='program',
            name='institution',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution'),
            preserve_default=False,
        ),
    ]
