# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0034_auto_20171117_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archiver', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutboundProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archiver', models.CharField(blank=True, max_length=32)),
                ('requirement_deadline', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='program',
            old_name='terms',
            new_name='terms_available',
        ),
        migrations.RemoveField(
            model_name='program',
            name='institution',
        ),
        migrations.AddField(
            model_name='program',
            name='is_graduate',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institution',
            name='contact_person_email',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='institution',
            name='contact_person_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='institution',
            name='contact_person_number',
            field=models.CharField(max_length=64),
        ),
        migrations.AddField(
            model_name='outboundprogram',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution'),
        ),
        migrations.AddField(
            model_name='outboundprogram',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Program'),
        ),
        migrations.AddField(
            model_name='inboundprogram',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Program'),
        ),
    ]
