# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-02 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0037_auto_20171201_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archiver', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.InboundProgram')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Requirement',
            new_name='OutboundRequirement',
        ),
    ]
