# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0038_auto_20171202_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboundrequirement',
            name='program',
        ),
        migrations.RemoveField(
            model_name='outboundrequirement',
            name='program',
        ),
    ]
