# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0039_auto_20171204_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboundrequirement',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='inboundrequirement',
            name='archiver',
        ),
        migrations.RemoveField(
            model_name='outboundrequirement',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='outboundrequirement',
            name='archiver',
        ),
    ]
