# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-05 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0040_auto_20171205_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outboundprogram',
            name='requirement_deadline',
        ),
    ]
